pub const instant_buy_asset_name: ByteArray = "InstantBuy"

pub const offer_asset_name: ByteArray = "OfferBuy"

pub const min_ada_value: Int = 2_000_000

pub const fixed_decimals: Int = 100

pub const fees_basis: Int = 250

pub const jam_on_bread_fee_portion: Int = 1_000

pub const listing_marketplace_portion: Int = 4_000

pub const listing_affiliate_portion: Int = 2_000

pub const selling_marketplace_portion: Int = 5_000
